name: Create and Commit to New Branch

on:
  push:
    branches:
      - main  # Define the trigger branch, adjust as needed

jobs:
  create_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create new branch
      run: git checkout -b fresh-branch
      
    - name: Replace text
      run: |
        with:
          find: "Hello Ramiz"
          replace: "Hello Ramiz Girach"
          regex: false
         
            
    - name: Authentication
      run: |
          git config --global user.email "ramizg.aipl@gmail.com"
          git config --global user.name "Ramiz Girach"
  
    - name: Commit changes
      run: |
        git add .
        git commit -m "Add new content"

    - name: Push changes to new branch
      run: |
        git push origin fresh-branch
        
        
