name: Create and Commit to New Branch
on:
  push:
    branches:
      - main
jobs:
  create_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Create new branch
        run: git checkout -b new-branch
      - name: Replace text
        run: |
            find . -type f -name '*.txt' -exec sed -i 's/Hello Ramiz/Hello Ramiz Girach/g' {} +

      - name: Authentication
        run: |
          git config --global user.email "ramizg.aipl@gmail.com"
          git config --global user.name "Ramiz Girach"
      - name: Commit changes
        run: |
          git add .
          git commit -m "Add new content 2"
      - name: Push changes to new branch
        run: |
          git push origin new-branch
          
